#!/bin/bash
# Webhook Forwarder - Project Summary & Commands

echo "==================================="
echo "   WEBHOOK FORWARDER PROJECT"
echo "==================================="
echo ""

# Display project structure
echo "📁 PROJECT STRUCTURE:"
echo "webhook-forwarder/"
echo "├── 📄 README.md                 # Full documentation"
echo "├── 📄 QUICKSTART.md             # 5-minute setup guide"
echo "├── 📄 DEPLOYMENT.md             # Production deployment"
echo "├── 📄 package.json              # Dependencies"
echo "├── 📄 .env.local                # Environment variables (local only)"
echo "├── 📄 .gitignore                # Git ignore patterns"
echo "├── 📄 next.config.js            # Next.js configuration"
echo "├── 📄 test-server.js            # Example webhook receiver"
echo "├── 📁 lib/"
echo "│   ├── mongodb.js               # MongoDB connection"
echo "│   ├── webhookService.js        # Webhook business logic"
echo "│   └── config.js                # Configuration & utilities"
echo "└── 📁 pages/"
echo "    ├── index.js                 # Dashboard UI"
echo "    └── 📁 api/"
echo "        ├── webhooks.js          # CRUD operations"
echo "        └── 📁 webhook/"
echo "            ├── [webhookId].js   # Webhook forwarding"
echo "            └── [webhookId]/logs.js  # Webhook logs"
echo ""

# Common commands
echo "🚀 QUICK START COMMANDS:"
echo ""
echo "1️⃣  Setup:"
echo "   npm install"
echo "   # Edit .env.local with your MongoDB URI"
echo ""
echo "2️⃣  Development:"
echo "   npm run dev"
echo "   # Opens http://localhost:3000"
echo ""
echo "3️⃣  Test Server (in another terminal):"
echo "   node test-server.js"
echo "   # Running on http://localhost:3001"
echo ""
echo "4️⃣  Production Build:"
echo "   npm run build"
echo "   npm start"
echo ""

# API endpoints
echo "📡 API ENDPOINTS:"
echo ""
echo "POST   /api/webhooks                    # Create webhook"
echo "GET    /api/webhooks                    # Get all webhooks"
echo "DELETE /api/webhooks                    # Delete webhook"
echo "POST   /api/webhook/[webhookId]         # Receive & forward webhook"
echo "GET    /api/webhook/[webhookId]/logs    # Get webhook logs"
echo ""

# Example curl commands
echo "🔧 EXAMPLE CURL COMMANDS:"
echo ""
echo "Create Webhook:"
echo '  curl -X POST http://localhost:3000/api/webhooks \'
echo '    -H "Content-Type: application/json" \'
echo '    -d '"'"'{"localhostPort": 3001, "description": "Test"}'"'"
echo ""
echo "Get All Webhooks:"
echo "  curl http://localhost:3000/api/webhooks"
echo ""
echo "Send Webhook:"
echo '  curl -X POST http://localhost:3000/api/webhook/abc123def456 \'
echo '    -H "Content-Type: application/json" \'
echo '    -d '"'"'{"event": "test.event", "data": "value"}'"'"
echo ""
echo "Get Webhook Logs:"
echo "  curl http://localhost:3000/api/webhook/abc123def456/logs"
echo ""

# Documentation links
echo "📚 DOCUMENTATION:"
echo ""
echo "  📖 Full Setup     → Read README.md"
echo "  ⚡ Quick Start    → Read QUICKSTART.md"
echo "  🚀 Deployment    → Read DEPLOYMENT.md"
echo "  🔌 API Reference → Check pages/api/"
echo ""

# Features
echo "✨ FEATURES:"
echo ""
echo "  ✅ Simple webhook registration"
echo "  ✅ Automatic forwarding to localhost"
echo "  ✅ Preserves all headers & body data"
echo "  ✅ Detailed logging of all requests"
echo "  ✅ MongoDB for data persistence"
echo "  ✅ Real-time dashboard UI"
echo "  ✅ RESTful API for programmatic access"
echo "  ✅ Support for Stripe, GitHub, and custom webhooks"
echo ""

# System requirements
echo "🔧 REQUIREMENTS:"
echo ""
echo "  • Node.js 16+"
echo "  • npm or yarn"
echo "  • MongoDB (local or MongoDB Atlas)"
echo "  • Modern web browser"
echo ""

# Troubleshooting
echo "🆘 TROUBLESHOOTING:"
echo ""
echo "1. MongoDB Connection Error?"
echo "   → Check MONGODB_URI in .env.local"
echo "   → Ensure MongoDB is running (if local)"
echo ""
echo "2. Webhook Not Forwarding?"
echo "   → Verify test server is running on correct port"
echo "   → Check webhook exists: curl http://localhost:3000/api/webhooks"
echo "   → View logs: curl http://localhost:3000/api/webhook/[id]/logs"
echo ""
echo "3. Port Already in Use?"
echo "   → Kill process: lsof -i :3000 | grep LISTEN | awk '{print \$2}' | xargs kill -9"
echo "   → Or use different port: PORT=3002 npm run dev"
echo ""

# Next steps
echo "📋 NEXT STEPS:"
echo ""
echo "1. Install dependencies: npm install"
echo "2. Configure MongoDB in .env.local"
echo "3. Start development server: npm run dev"
echo "4. Visit http://localhost:3000"
echo "5. Create your first webhook!"
echo ""

# Support
echo "❓ NEED HELP?"
echo ""
echo "  • Check README.md for comprehensive documentation"
echo "  • Review QUICKSTART.md for common scenarios"
echo "  • See DEPLOYMENT.md for production setup"
echo "  • Check test-server.js for webhook handler examples"
echo ""

echo "==================================="
echo "         Happy Webhooking! 🎉"
echo "==================================="
